--- #YAML:1.0
name:               Acme-Very-Modern-Perl
version:            0.04
abstract:           Use the most modern of Perl!
author:
    - Frank Wiegand <frank.wiegand@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    common::sense:  0
    latest:         0
    Modern::Perl:   0
    perl5i:         v1.0.0
    Test::More:     0
    Toolkit:        0
    uni::perl:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
